{
  participatoryProcesses(
    filter: { publishedSince: "2023-09-12", publishedBefore: "2023-09-14" }
  ) {
    id
    slug
    publishedAt
    stats {
      name
      value
    }
    components(filter: { name: "Propostes Ciutadanes" }) {
      id
      name {
        translation(locale: "ca")
      }
      ... on Proposals {
        proposals {
          edges {
            node {
              ... on Proposal {
                id
                state
                author {
                  name
                }
                title {
                  translation(locale: "ca")
                }
                body {
                  translation(locale: "ca")
                }
                category {
                  id
                  name {
                    translation(locale: "ca")
                  }
                }
                voteCount
                comments {
                  id
                  author {
                    name
                  }
                  body
                  alignment
                  comments {
                    id
                    author {
                      name
                    }
                    body
                    alignment
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
